apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: pod-inspect
spec:
  version: v0.1.7
  homepage: https://github.com/jpriebe/kubectl-pod-inspect
  shortDescription: Get all of a pod's details at a glance
  description: |
    Provides detailed information about a pod, including its containers' statuses,
    pod events, and logs from non-ready containers.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/jpriebe/kubectl-pod-inspect/releases/download/v0.1.7/kubectl-pod-inspect_0.1.7_Darwin_x86_64.tar.gz
    sha256: ec62b259d971b63de10cb367ed4547374b1d5c908886f258663ff000c4338e4d
    bin: kubectl-pod_inspect
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/jpriebe/kubectl-pod-inspect/releases/download/v0.1.7/kubectl-pod-inspect_0.1.7_Linux_x86_64.tar.gz
    sha256: f44ebb1e99109f88e9aee6c60749d78ecf6c6f6764f194d5e0082d8bca25503d
    bin: kubectl-pod_inspect
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/jpriebe/kubectl-pod-inspect/releases/download/v0.1.7/kubectl-pod-inspect_0.1.7_Windows_x86_64.tar.gz
    sha256: 1b9872c91d39bdba47b5c43ceccb0fdae39af3903336813cdc59974edfe6b324
    bin: kubectl-pod_inspect.exe

