apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: pod_inspect
spec:
  version: v0.1.6
  homepage: https://github.com/jpriebe/kubectl-pod_inspect
  shortDescription: Get all of a pod's details at a glance
  description: |
    Provides detailed information about a pod, including its containers' statuses, pod events, and logs from non-ready containers.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/jpriebe/kubectl-pod_inspect/releases/download/v0.1.6/kubectl-pod_inspect_0.1.6_Darwin_x86_64.tar.gz
    sha256: 0e62b98cb601415a7fd9d972a786a7023d8b42d30064a683023ad8b8d0dea90f
    bin: kubectl-pod_inspect
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/jpriebe/kubectl-pod_inspect/releases/download/v0.1.6/kubectl-pod_inspect_0.1.6_Linux_x86_64.tar.gz
    sha256: 08b924c3962dbb82bed25416f1d6496ae16cfd741540d025d30878c5e3490a12
    bin: kubectl-pod_inspect
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/jpriebe/kubectl-pod_inspect/releases/download/v0.1.6/kubectl-pod_inspect_0.1.6_Windows_x86_64.tar.gz
    sha256: 28e47d161e7f697d5a29b429082396c648bd8a7260c81a6b114099bf4e91e3bc
    bin: kubectl-pod_inspect.exe
